---
- hosts:
    - linux_backup_servers
    - lxd_hosts
    - linux_containers
  sudo: False
  connection: ssh

  tasks:
    - name: check network settings
      block:
        - name: Check Netplan
          shell: cat /etc/netplan/*
          register: response
        - debug: msg="{{response.stdout_lines | replace(' \\\\n \\\\l','') }}"
      rescue:
        - name: Check ifup
          shell: cat /etc/network/interfaces
          register: response
        - debug: msg="{{response.stdout_lines | replace(' \\\\n \\\\l','') }}"
